name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./food-delivery-springboot-web
        run: mvn -B clean package -DskipTests

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCES_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./food-delivery-springboot-web
          file: ./food-delivery-springboot-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/food-delivery-backend:latest
          build-args: |
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AW5_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
            FRONT_END_ADMIN=${{ secrets.FRONT_END_ADMIN }}
            FRONT_END_USER=${{ secrets.FRONT_END_USER }}
            JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            RAZORPAY_SECRET_KEY=${{ secrets.RAZORPAY_SECRET_KEY }}
            RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}
            SEND_TO_EMAIL=${{ secrets.SEND_TO_EMAIL }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}?imgUrl=docker.io/${{ secrets.DOCKER_USERNAME }}/food-delivery-backend:latest"
